version: "3"

services:
  # App frontend service
  front:
    build:
      context: frontend
      dockerfile: ./Dockerfile.web
    ports:
      - "8888:3000"
    restart: always
    depends_on:
      - api
    environment:
      NODE_ENV: production
      PORT: 3000
    networks:
      - frontend
  # App backend service
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: postgres://postgres:@db:5432/meiup
    networks:
      - backend
      - frontend
  # Database Service (postgres)
  db:
    image: "postgres:latest"
    restart: always
    user: postgres
    container_name: "meiup_api"
    ports:
      - "54321:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: meiup
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      - backend
volumes:
  meiup-data:
networks:
  backend:
  frontend:
